#
# Defines environment variables.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Ensure that a non-login, non-interactive shell has a defined environment.
if [[ ( "$SHLVL" -eq 1 && ! -o LOGIN ) && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi

export RBENV_ROOT=/usr/local/var/rbenv

export VIRTUALENVWRAPPER_PYTHON=/usr/local/bin/python3
export PYENV_VIRTUALENV_DISABLE_PROMPT=1
export NVM_DIR=~/.nvm

if [[ -f "/usr/local/etc/openssl/cert.pem" ]]; then
  export SSL_CERT_FILE=/usr/local/etc/openssl/cert.pem
  export REQUESTS_CA_BUNDLE=/usr/local/etc/openssl/cert.pem
  export WEBSOCKET_CLIENT_CA_BUNDLE=/usr/local/etc/openssl/cert.pem
fi

if [[ -s "${ZDOTDIR:-$HOME}/.zsecret" ]]; then
    source "${ZDOTDIR:-$HOME}/.zsecret"
fi

export NODE_EXTRA_CA_CERTS=/etc/ssl/certs/palantir-ca-bundle.crt
export EDITOR=vim

path=(~/.jetbrains $path)
export PATH
