#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
setopt NO_NOMATCH

if which rbenv > /dev/null; then eval "$(rbenv init -)"; fi
alias npm-exec='PATH=$(npm bin):$PATH'

giaw () { git diff -w --no-color "$@" | git apply --cached --ignore-whitespace}

ds () {
    eval $(docker-machine env default)
}
dc () {
    docker rmi $(docker images | grep '^<none>' | awk '{ print $3 }')
}
dr () {
    docker rm $(docker ps -a -q)
}
PATH=$PATH:$HOME/.rvm/bin # Add RVM to PATH for scripting

# Added by Krypton
export GPG_TTY=$(tty)

# The next line updates PATH for the Google Cloud SDK.
if [ -f '/Users/akarnani/google-cloud-sdk/path.zsh.inc' ]; then . '/Users/akarnani/google-cloud-sdk/path.zsh.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/Users/akarnani/google-cloud-sdk/completion.zsh.inc' ]; then . '/Users/akarnani/google-cloud-sdk/completion.zsh.inc'; fi
